version: '3'

services:
  redis:
    container_name: redis_integration
    command: redis-server --port 6380
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    volumes:
      - ${REDIS_DATA_DIR-./data/redis}:/data
    expose:
      - 6380
    ports:
        - "6380:6379"
    networks:
      - microNetwork
  api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    env_file:
      - .env
    networks:
      - microNetwork
    volumes:
      - ./apps/api:/apps/api
    ports:
      - "8080:8080"

networks:
  microNetwork:


